=== iqmmug/iqm/application/iqm-api/src/main/resources/xsd/IQMOperatorTemplates.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  #%L
  Project: IQM - API
  File: IQMOperatorTemplates.xsd
  
  $Id$
  $HeadURL$
  
  This file is part of IQM, hereinafter referred to as "this program".
  %%
  Copyright (C) 2009 - 2021 Helmut Ahammer, Philipp Kainz
  %%
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as
  published by the Free Software Foundation, either version 3 of the
  License, or (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public
  License along with this program.  If not, see
  <http://www.gnu.org/licenses/gpl-3.0.html>.
  #L%
  -->


<!--
  	Author: Philipp Waltl
-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://xml.netbeans.org/schema/iqmOperatorTemplates"
    xmlns:tns="http://xml.netbeans.org/schema/iqmOperatorTemplates"
    elementFormDefault="qualified">
    <xsd:complexType name="iqmOperatorDescriptor">
        <xsd:sequence>
            <xsd:element name="parameters" minOccurs="0" maxOccurs="unbounded" nillable="false">
                <xsd:complexType>
                    <xsd:attribute name="parametername" type="xsd:string" use="required"/>
                    <xsd:attribute name="parameterclass" type="xsd:string" use="required"/>
                    <xsd:attribute name="parametervalue" type="xsd:string" use="required"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="templatename" type="xsd:string"/>
    </xsd:complexType>
    <xsd:element name="iqmOperatorTemplates">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="parameterBlock" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="template" type="tns:iqmOperatorDescriptor" maxOccurs="unbounded"></xsd:element>
                        </xsd:sequence>
                        <xsd:attribute name="blockname" type="xsd:string"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== iqmmug/iqm/branches/iqm4/application/iqm-api/src/main/resources/xml/IQMOperatorTemplates.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
  #%L
  Project: IQM - API
  File: IQMOperatorTemplates.xml
  
  $Id$
  $HeadURL$
  
  This file is part of IQM, hereinafter referred to as "this program".
  %%
  Copyright (C) 2009 - 2017 Helmut Ahammer, Philipp Kainz
  %%
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as
  published by the Free Software Foundation, either version 3 of the
  License, or (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public
  License along with this program.  If not, see
  <http://www.gnu.org/licenses/gpl-3.0.html>.
  #L%
  -->

<!-- Document : IQMOperatorTemplates.xml Created on : 23. Oktober 2010, 12:34 Author 
	: WaltPh, altered 2013-03-23, Philipp Kainz. Description: Purpose of the document follows. -->

<ns0:iqmOperatorTemplates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:ns0="http://xml.netbeans.org/schema/iqmOperatorTemplates"
	xsi:schemaLocation="http://xml.netbeans.org/schema/iqmOperatorTemplates IQMOperatorTemplates.xsd">
	<ns0:parameterBlock blockname="">
		<ns0:template templatename="">
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
		</ns0:template>
		<ns0:template templatename="">
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
		</ns0:template>
		<ns0:template templatename="">
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
		</ns0:template>
	</ns0:parameterBlock>
	<ns0:parameterBlock blockname="">
		<ns0:template templatename="">
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
		</ns0:template>
		<ns0:template templatename="">
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
		</ns0:template>
		<ns0:template templatename="">
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
		</ns0:template>
	</ns0:parameterBlock>
	<ns0:parameterBlock blockname="">
		<ns0:template templatename="">
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
		</ns0:template>
		<ns0:template templatename="">
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
		</ns0:template>
		<ns0:template templatename="">
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
			<ns0:parameters parametername="" parameterclass=""
				parametervalue="" />
		</ns0:template>
	</ns0:parameterBlock>

</ns0:iqmOperatorTemplates>
